appcelerator/HAL

examples/CMakeLists.txt, examples/ChildWidget.cpp, examples/ChildWidget.hpp, include/HAL/JSContext.hpp, include/HAL/JSValue.hpp, include/HAL/detail/JSExportCallbacks.hpp, src/JSContext.cpp, src/JSValue.cpp, test/JSExportTests.cpp, test/JSObjectTests.cpp, test/JSValueTests.cpp, xcode/HAL.xcodeproj/project.pbxproj, xcode/HALTests/JSExportTests.mm, xcode/HALTests/JSObjectTests.mm, xcode/HALTests/JSValueTests.mm
Related to #42. JSExport class should have had a way to forward property request to prototype chain. Added `CreateNativeNull()` so that you can mark it as "delegate to parent". 
```c++
JSValue GlobalObject::getXXXProperty(const JSString& property_name) const
{
if (property_name == "i_want_null") {
return get_context().CreateNull();
} else if (property_name == "i_want_undefined") {
return get_context().CreateUndefined();
} else if (property_name == "i_want_prototype_chain") {
return get_context().CreateNativeNull();
}
...
}
```
=> Add suport for JSExport "delegate to parent" property

CMakeLists.txt, README.md, build_ios.sh, cmake/internal_utils_xcode.cmake
Added build script for iOS static library for both simulator and device.
```bash
$ cd YOUR_HAL_DIR
$ ./build_ios.sh
$ ls -la build.debug/libHAL.a 
```
`build_ios.sh` builds iOS static library for iPhone simulator by default. If you need a static library for the device, edit `build_ios.sh` and change `ARCH` and `PLATFORM` variables.
```bash
#cmd+=" -DARCH=i386 -DPLATFORM=iphonesimulator"
cmd+=" -DARCH=arm64 -DPLATFORM=iphoneos"
```
=> Add build script for iOS static library

README.md, test/JSContextTests.cpp
It was originally because JavaScriptCore returns wrong value for `new Date()` so we just need to upgrade the library.
=> [TIMOB-18855] Fix: new Date() returns wrong value

include/HAL/JSArray.hpp, include/HAL/JSContext.hpp, include/HAL/JSFunction.hpp, include/HAL/JSObject.hpp, src/JSArray.cpp, src/JSContext.cpp, src/JSFunction.cpp, test/JSObjectTests.cpp, xcode/HALTests/JSObjectTests.mm
Feedback from [titanium_mobile_windows](https://github.com/appcelerator/titanium_mobile_windows).
-  Add JSArray to `std::vector` of primitive types conversion 
- Add JSFunction::CreateFunction(JSFunctionCallback))
JSFunction::CreateFunction is a convenience method for creating a JavaScript function with a given callback as its implementation by C++ lambda/std::function etc. It is conceptually C++11 version of `JSObjectMakeFunctionWithCallback` JavaScriptCore C API.
```c++
JSContext js_context = js_context_group.CreateContext();
JSFunctionCallback callback = [js_context](const std::vector<JSValue> arguments, JSObject& this_object) {
return js_context.CreateString("Hello, "+static_cast<std::string>(arguments.at(0)));
};
JSFunction js_function = js_context.CreateFunction(callback); …
```
=> Shorthand for creating a JS function with a given native callback

include/HAL/JSContext.hpp, include/HAL/JSContextGroup.hpp, include/HAL/JSObject.hpp, include/HAL/JSValue.hpp, test/JSContextTests.cpp, test/JSObjectTests.cpp, test/JSValueTests.cpp
explicit conversion between pointer.
- JSContextGroup
- JSContext
- JSObject
- JSValue
This is needed especially for the values to be passed across WinRT boundary on Windows.
```c++
JSContext js_context = js_context_group.CreateContext();
auto context_ref = static_cast<JSContextRef>(js_context);
auto context_ptr = reinterpret_cast<std::intptr_t>(context_ref);
auto js_context2 = JSContext(reinterpret_cast<JSContextRef>(context_ptr));
XCTAssertTrue(js_context == js_context2);
```
=> Implement explicit conversion between pointer

src/JSObject.cpp
Fix for [TIMOB-19216](https://jira.appcelerator.org/browse/TIMOB-19216)
`std::unordered_map::emplace` should not be used to replace elements because it works only when key is unique.
=> Fix: Wrong use of std::unordered_map::emplace

test/JSExportTests.cpp, test/JSObjectTests.cpp, test/JSValueTests.cpp
Making sure HAL types and JSExport objects support `JSON.stringify`.
=> Add unit test for JSON.stringify

include/HAL/JSContextGroup.hpp, src/JSContextGroup.cpp, src/JSFunction.cpp, test/JSObjectTests.cpp
- Give name to anonymous function
- Don't `JSContextGroupRelease` when it's not `JSContextGroupRetain`-ed
=> Fix HAL unit tests on latest JavaScriptCore

include/HAL/detail/JSBase.hpp
I would define like this because only Mac/iOS uses "builtin" JavaScriptCore.
=> Fix inconsistent definition warning on Windows

include/HAL/JSString.hpp, src/JSString.cpp, test/JSStringTests.cpp
Cleanup JSString API regarding u16string. Currently JSString keeps reference to `std::u16string` as well as `std::string` but I don't think we want to keep `u16string` as member of JSString.  I also think conversion operator between `u16string` is not necessary when thinking about current usage. We can just deal with utf-8 through std::string.
- Remove u16string related function/variable from JSString
- Make JSString to JSStringRef API public, just like JSValue/JSObject does.
=> JSString u16string API cleanup

src/JSString.cpp, test/JSStringTests.cpp
JSString should use JSStringGetUTF8CString instead of JSStringGetCharactersPtr.
=> Fix: JSString should use UTF-8 string

CMakeLists.txt
Part of [TIMOB-20201](https://jira.appcelerator.org/browse/TIMOB-20201)
We have been disabling SAFESEH linker option just to supress compiler warning message for simulator according to CMakeLists.txt#L195. This PR enables `SAFESEH` for Windows Phone/Store app so it passes Windows App Certification.
=> Enable SAFESEH for Windows Store/Phone build

examples/ChildWidget.cpp, examples/ChildWidget.hpp, examples/Widget.cpp, examples/Widget.hpp, include/HAL/JSExport.hpp, include/HAL/detail/JSExportCallbacks.hpp, include/HAL/detail/JSExportClass.hpp, include/HAL/detail/JSExportClassDefinition.hpp, include/HAL/detail/JSExportClassDefinitionBuilder.hpp, test/JSExportTests.cpp
Part of [TIMOB-20256](https://jira.appcelerator.org/browse/TIMOB-20256).
From the starting point of HAL, we have been declaring proxy property using C++ object member by holding `JSValue`.
```c++
class Widget : public JSExportObject, public JSExport<Widget> {
private:
JSValue myProperty_1__;
JSValue myProperty_2__;
};
```
In this case we are creating these instances at proxy constructor:
```c++
Widget::Widget(const JSContext& js_context) HAL_NOEXCEPT
: JSExportObject(js_context)
, myProperty_1__(js_context.CreateObject())
, myProperty_2__(js_context.CreateNumber()) {
}
```
Getter would be implemented like below. We are storing `JSValue` in C++ member, and this makes sense because we don't want to create new JSValue every time getter is called.
```c++
JSValue Widget::js_get_myProperty1() …
```
=> Implement property cache

examples/OtherWidget.cpp, examples/OtherWidget.hpp, include/HAL/JSExport.hpp, include/HAL/detail/JSExportClass.hpp, test/JSExportTests.cpp
[TIMOB-20316](https://jira.appcelerator.org/browse/TIMOB-20316)
Simple implementation for LRU cache for constant properties. This also provides some functions to evict cache explicitly, which might be useful when you want to clear caches when app is no longer active (i.e. at suspend event).
- `HAL::detail::JSExportClass<T>::EvictCache()`
- `HAL::detail::JSExportClass<T>::EvictAllCache()`
- `HAL::detail::JSExportClass<T>::ResizeCache(std::uint_t)`
- `HAL::detail::JSExportClass<T>::GetCachedKeys()`
And added shortcut for `EvictAllCache` from `JSExport<T>`
- `JSExport<T>::EvictAllCache()`
=> Implement LRU constant cache

src/JSContext.cpp, src/JSContextGroup.cpp
Introduce "single context mode", which basically disables retain/release for JS context and context group. This does _huge_ performance improvement especially on TitaniumKit, because only one context (global context) is actually used in TitaniumKit and there's no need to retain/release it.
In order to enable this, just define `HAL_USE_SINGLE_CONTEXT` before including `HAL.hpp`.
=> Introduce single context mode

include/HAL/JSValue.hpp, src/JSObject.cpp, src/JSValue.cpp
Manage retain count for `JSValue` and `JSObject`, and avoid issuing `JSValueProtect/Unprotect` whenever possible. 
This gains 20~30% performance improvement on my WP8.1 Lumia.
=> Avoid JSValue(Un)Protect whenever possible

include/HAL/detail/JSExportClass.hpp
Related to [TIMOB-23621](https://jira.appcelerator.org/browse/TIMOB-23621)
When proxy function throws c++ exception, HAL should catch it and update `*exception` to `JSError` with function name. This should help to provide better log message.
=> Catch exception and save function name at function callback

src/JSObject.cpp
JSObject was to be protected more than twice on race condition.
=> Avoid race condition at protecting JSObject

include/HAL/detail/JSExportClass.hpp, test/JSContextTests.cpp, test/JSExportTests.cpp
When JSExport object is instantiated via `new`, new object should have `constructor` property and it should point to the actual constructor.
```javascript
var widget = new Widget();
should(widget.constructor == Widget).be.true;
```
=> Implement "constructor" property

include/HAL/JSValue.hpp, src/JSValue.cpp
Follow up on https://github.com/appcelerator/HAL/issues/70
Annotate `JSValue::ToJSONString()` as a `const` just like `JSValue::JString()`
=> HAL Issues#70 `JSValue::ToJSONString()` should be `const`

examples/Widget.cpp, examples/Widget.hpp, include/HAL/JSExport.hpp, test/JSExportTests.cpp
When you want to set `enumerable=false` to the property on your `JSExport` class, it is not actually passed to `JSExport`. That makes it impossible to define non-enumerable property.
=> enumerable property is not passed to JSExport
